LOADING_MESSAGES = [
    "Crunching the latest data",
    "Stealing Dobby's socks",
    "Coaching Sayed on his job hunt",
    "Forecasting meme outlook for the next week",
    "... so what are you doing here again?",
    "Going for a jog - you should too!",
    "Calculating purchasing power of turnips from Daisy Mae",
    "Forecasting turnip purchase prices for this Sunday",
    "Loading up a nice warm game of League of Legends",
    "Switching to Dota 2 because League is toxic AF",
    "Time for a movie",
    "Making coffee, nevermind Starbucks go brrr",
    "Tilting my roommate by ordering delivery from a Starbucks across from my house",
    "Crunching the numbers on emoji data",
    "Planning a trip to Austin",
    "Wreaking havoc on the Discord channel by making everyone an admin",
    "Selecting runes for Tristana",
    "Using Sayed's credit card to buy more Frozen toys from Amazon",
    "Looking for Elsa's water horse...",
    "Loading up Frozen 2 on Robert's computer",
    "Persisting emoji data to disk for eternity",
    "Buying plane tickets to New York",
    "Calculating turnip profits for this week",
    "Buying a new black leather sofa from IKEA for Sayed's apartment",
    "Using bIIIg computer brain to calculate the probability of Big Chick winning on Ryze",
    "Did you know when POGPLANT is spammed in the channel, Big Chick's power increases exponentially on Darius?",
    "Spamming POGPLANTS in Discord",
    "POGPLANT",
    "Making an nice espresso to spill on Sayed's jacket",
    "Running late for a dinner appointment at Golden Diner",
    "Sitting in a room that smells like urinal cakes",
    "Crunching the latest data on emoji usage within HTV",
    "Searching for the latest emojis and memes",
    "Caching emojis and meme data",
    "Writing David Attenborough and Steve Carroll-esqe nature articles",
    "FU Jook",
    "Tilting Sayed by working on ElsaBot"
]
